# https://taskfile.dev
#
# Taskfile wrappers for gh CLI and other commands used by Claude Code.
# Compound shell commands (redirects, pipes, chaining) break Claude's
# permission pattern matching. These tasks encapsulate those commands
# so Claude can invoke a single, matchable command like:
#
#   task -d ~/dev/oce/oce-tasks/main gh:issues
#
# Install: https://taskfile.dev/installation/

version: '3'

vars:
  OUTPUT_DIR: '{{.OUTPUT_DIR | default (printf "%s/dev/openemr/triage" .HOME)}}'
  REPO: openemr/openemr

  # Fields fetched for issues (keep in sync with sync-triage/quick-sync-triage skills)
  ISSUE_FIELDS: number,title,state,author,createdAt,updatedAt,labels,body,comments,reactionGroups,closedByPullRequestsReferences,issueType

  # Fields fetched for PRs (keep in sync with sync-triage/quick-sync-triage skills)
  # Note: statusCheckRollup is intentionally excluded — it causes GitHub API
  # timeouts (HTTP 504) on repos with many open PRs. ciStatus is derived via
  # gh pr view on individual PRs when needed during triage instead.
  PR_FIELDS: number,title,state,author,createdAt,updatedAt,labels,body,mergeable,reviewDecision,isDraft,changedFiles,additions,deletions,maintainerCanModify,comments,reactionGroups,closingIssuesReferences

tasks:
  # === GitHub Issues ===

  gh:issues:
    desc: Fetch all open issues and write to OUTPUT_DIR/issues.json
    silent: true
    cmds:
      - >-
        gh issue list
        --repo {{.REPO}}
        --state open
        --limit 500
        --json {{.ISSUE_FIELDS}}
        > "{{.OUTPUT_DIR}}/issues.json"
      - echo "Wrote $(jq length "{{.OUTPUT_DIR}}/issues.json") issues to {{.OUTPUT_DIR}}/issues.json"

  gh:issues:since:
    desc: 'Fetch open issues updated since SINCE timestamp (usage: task gh:issues:since SINCE=2026-01-01T00:00:00Z)'
    silent: true
    requires:
      vars: [SINCE]
    cmds:
      - >-
        gh issue list
        --repo {{.REPO}}
        --state open
        --limit 500
        --json {{.ISSUE_FIELDS}}
        --jq '[.[] | select(.updatedAt > "{{.SINCE}}")]'
        > "{{.OUTPUT_DIR}}/issues.json"
      - echo "Wrote $(jq length "{{.OUTPUT_DIR}}/issues.json") issues (since {{.SINCE}}) to {{.OUTPUT_DIR}}/issues.json"

  # === GitHub Pull Requests ===

  gh:prs:
    desc: Fetch all open PRs and write to OUTPUT_DIR/prs.json
    silent: true
    cmds:
      - >-
        gh pr list
        --repo {{.REPO}}
        --state open
        --limit 500
        --json {{.PR_FIELDS}}
        > "{{.OUTPUT_DIR}}/prs.json"
      - echo "Wrote $(jq length "{{.OUTPUT_DIR}}/prs.json") PRs to {{.OUTPUT_DIR}}/prs.json"

  gh:prs:since:
    desc: 'Fetch open PRs updated since SINCE timestamp (usage: task gh:prs:since SINCE=2026-01-01T00:00:00Z)'
    silent: true
    requires:
      vars: [SINCE]
    cmds:
      - >-
        gh pr list
        --repo {{.REPO}}
        --state open
        --limit 500
        --json {{.PR_FIELDS}}
        --jq '[.[] | select(.updatedAt > "{{.SINCE}}")]'
        > "{{.OUTPUT_DIR}}/prs.json"
      - echo "Wrote $(jq length "{{.OUTPUT_DIR}}/prs.json") PRs (since {{.SINCE}}) to {{.OUTPUT_DIR}}/prs.json"
